INSERT INTO genres
VALUES (0, 'Horror'),
       (1, 'Adventure'),
       (2, 'Shooter'),
       (3, 'Sandbox'),
       (4, 'RTS'),
       (5, 'MOBA'),
       (6, 'RPG'),
       (7, 'Simulation'),
       (8, 'Sport'),
       (9, 'Puzzle'),
       (10, 'Action'),
       (11, 'Survival '),
       (12, 'Platformer'),
       (13, 'RTT'),
       (14, 'Fighting'),
       (15, 'Brawler'),
       (16, 'Stealth'),
       (17, 'Rhythm'),
       (18, 'Battle royale'),
       (19, 'Metroidvania'),
       (20, 'Visual novel'),
       (21, 'Interactive movie'),
       (22, 'Coding'),
       (23, 'Tile-matching'),
       (24, 'MMORPG'),
       (25, 'Roguelike'),
       (26, 'Construction'),
       (27, 'Strategy'),
       (28, 'Tower defense'),
       (29, 'Turn-based strategy'),
       (30, 'Turn-based tactics'),
       (31, 'Wargame'),
       (32, 'Racing'),
       (33, 'Board'),
       (34, 'Card'),
       (35, 'Casino'),
       (36, 'Casual'),
       (37, 'Gacha'),
       (38, 'Idle'),
       (39, 'Social deduction'),
       (40, 'Art'),
       (41, 'Educational'),
       (42, 'Creative'),
       (43, 'Open world'),
       (44, 'Shoot `em up'),
       (45, 'Hack & Slash'),
       (46, 'Third-Person Shooter'),
       (47, 'First-Person Shooter'),
       (48, 'Role-Playing'),
       (49, 'JRPG'),
       (50, 'Rogue-Like'),
       (51, 'Adventure RPG'),
       (52, 'Farming'),
       (53, 'Physics'),
       (54, 'Space'),
       (55, 'Fishing'),
       (56, 'Hunting'),
       (57, 'MMO'),
       (58, 'Multiplayer'),
       (59, 'Singleplayer'),
       (60, 'Sci-Fi'),
       (61, 'Mystery'),
       (62, 'Detective'),
       (63, 'Cyberpunk'),
       (64, 'Nature'),
       (65, 'Co-op'),
       (66, 'Online Co-op'),
       (67, 'First Person'),
       (68, 'Third Person'),
       (69, 'Anime'),
       (70, 'Character Customization'),
       (71, 'Exploration'),
       (72, 'Fantasy'),
       (73, 'Atmospheric'),
       (74, 'Cinematic'),
       (75, 'PvE'),
       (76, 'PvP'),
       (77, 'Futuristic');