INSERT INTO genres
VALUES (0, 'Horror'),
       (1, 'Adventure'),
       (2, 'Shooter'),
       (3, 'Sandbox'),
       (4, 'RTS'),
       (5, 'MOBA'),
       (6, 'RPG'),
       (7, 'Simulation'),
       (8, 'Sport'),
       (9, 'Puzzle'),
       (10, 'Action'),
       (11, 'Survival '),
       (12, 'Platformer'),
       (13, 'RTT'),
       (14, 'Fighting'),
       (15, 'Brawler'),
       (16, 'Stealth'),
       (17, 'Rhythm'),
       (18, 'Battle royale'),
       (19, 'Metroidvania'),
       (20, 'Visual novel'),
       (21, 'Interactive movie'),
       (22, 'Coding'),
       (23, 'Tile-matching'),
       (24, 'MMORPG'),
       (25, 'Roguelike'),
       (26, 'Construction'),
       (27, 'Strategy'),
       (28, 'Tower defense'),
       (29, 'Turn-based strategy'),
       (30, 'Turn-based tactics'),
       (31, 'Wargame'),
       (32, 'Racing'),
       (33, 'Board'),
       (34, 'Card'),
       (35, 'Casino'),
       (36, 'Casual'),
       (37, 'Gacha'),
       (38, 'Idle'),
       (39, 'Social deduction'),
       (40, 'Art'),
       (41, 'Educational'),
       (42, 'Creative'),
       (43, 'Open world');
